version: '3.7'
services:
  # api backend
  api:
    container_name: api-service
    restart: unless-stopped
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    networks:
      - api_network
    environment:
      NODE_ENV: production
    depends_on:
      - postgres-db
  # client
  nextjs:
    container_name: client-service
    restart: unless-stopped
    build:
      context: ./client-next
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    networks:
      - api_network
    environment:
      NODE_ENV: production
    depends_on:
      - postgres-db
      - api

  # Nginx server
  nginx:
    container_name: nginx-service
    restart: unless-stopped
    image: nginx:stable-alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - api_network
    depends_on:
      - nextjs
      - api
  # Database
  postgres-db:
    container_name: db-postgres
    restart: unless-stopped
    image: postgres:14.8-alpine3.18
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: 'auth-db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d auth-db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - api_network
  # Web gui pg
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@root.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - docker-pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    depends_on:
      - postgres-db
    networks:
      - api_network

volumes:
  pg_data:
  docker-pgadmin:

networks:
  api_network:
    external: true
