# Base image для разработки
FROM node:20.11-alpine AS base

# Рабочая директория для проекта
WORKDIR /var/www/client-next

# Копируем package.json и устанавливаем все зависимости (включая dev-зависимости)
COPY package*.json ./
RUN npm install

# Копируем весь проект
COPY . .

# Expose порта для разработки
EXPOSE 3001

# Используем команду для запуска в режиме разработки
CMD ["npm", "run", "dev"]
