FROM node:20.11-alpine AS base
WORKDIR /var/www/client-next
RUN npm i
COPY . .
RUN npm build

FROM node:20.11-alpine as release
WORKDIR /var/www/client-next

COPY --from=base /var/www/client-next/node_modules ./node_modules
COPY --from=base /var/www/client-next/package.json ./package.json
COPY --from=base /var/www/client-next/.next ./.next

EXPOSE 3001

CMD ["npm", "start"]
