version: '3.7'
services:
  # Api application nest.js
  api:
    container_name: api-service
    restart: unless-stopped
    build:
      context: '.'
      dockerfile: 'Dockerfile.dev'
    links:
      - postgres-db
    ports:
      - '81:4000'
    networks:
      - 'api_network'
    volumes:
      - './:/var/www/back-end-api'

  # Database
  postgres-db:
    container_name: db-postgres
    restart: unless-stopped
    image: postgres:14.8-alpine3.18
    environment:
      TZ: 'Europe/Moscow'
      POSTGRES_DB: 'auth-db'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U root -d auth-db']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - '5432:5432'
    volumes:
      - './db_data:/var/lib/postgresql/data'
    networks:
      - api_network

  # Web gui pg
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: 'root@root.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - docker-pgadmin:/var/lib/pgadmin
    ports:
      - '5050:80'
    restart: unless-stopped
    depends_on:
      - postgres-db
    networks:
      - api_network

volumes:
  docker-pgadmin:

networks:
  api_network:
    external: true
